function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(1)=0;
    R_ss=1/params(2)-(1-params(3));
    K_N_ratio=(params(1)/R_ss)^(1/(1-params(1)));
    Y_N_ratio=exp(ys_(1))*K_N_ratio^params(1);
    W_ss=(1-params(1))*Y_N_ratio;
    C_N_ratio=Y_N_ratio-params(3)*K_N_ratio;
    ys_(5)=(W_ss/(C_N_ratio*params(6)))^(1/(1+params(4)));
    ys_(4)=K_N_ratio*ys_(5);
    ys_(8)=Y_N_ratio*ys_(5);
    ys_(2)=C_N_ratio*ys_(5);
    ys_(7)=W_ss;
    ys_(6)=R_ss;
    ys_(3)=params(3)*ys_(4);
    % Auxiliary equations
end
